name: Build and deploy .NET Core application to Web App SriFunDooWebApp with API Management Service FunDooNoteAppapi-FunDooNoteApp

on:
  push:
    branches:
      - master

env:
  AZURE_WEBAPP_NAME: SriFunDooWebApp
  AZURE_WEBAPP_PACKAGE_PATH: .\publish
  AZURE_APIM_RESOURCE_PATH: /SRI
  AZURE_APIM_RESOURCEGROUP: SRIFunDooNotes_group
  AZURE_APIM_SERVICENAME: FunDooNoteAppapi
  AZURE_APIM_API_ID: FunDooNoteApp
  AZURE_APIM_APPSERVICEURL: https://srifundoowebapp.azurewebsites.net
  SWASHBUCLE_ASPNET_CORE_CLI_PACKAGE_VERSION: 5.6.3
  SWASHBUCKLE_DOTNET_CORE_VERSION: 3.1.x
  API_IMPORT_SPECIFICATION_PATH: .\publish\swagger.json
  API_IMPORT_DLL: .\bin\Release\netcoreapp3.1\FunDooNote.dll
  API_IMPORT_VERSION: v1
  CONFIGURATION: Release
  DOTNET_CORE_VERSION: 5.0.x
  WORKING_DIRECTORY: .

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v1.8.0
        with:
          include-prerelease: True
          dotnet-version: ${{ env.DOTNET_CORE_VERSION }}

      - name: Setup SwashBuckle .NET Core
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: ${{ env.SWASHBUCKLE_DOTNET_CORE_VERSION }}

      - name: Generate Swagger
        run: |
          swagger tofile --output "C:\Users\SREEDHAR\Desktop\repos\FunDooNoteApp\FunDooNoteApp\bin\Release\netcoreapp3.1\swagger.json" "C:\Users\SREEDHAR\Desktop\repos\FunDooNoteApp\FunDooNoteApp\bin\Release\netcoreapp3.1\FunDooNoteApp.dll" "v1"

      - name: Restore
        run: dotnet restore ${{ env.WORKING_DIRECTORY }}

      # ... continue with the remaining steps (Build, Test, Publish, Install Swashbuckle CLI, Generate Open API Specification, Publish Artifacts)

  deploy:
    runs-on: windows-latest
    needs: build
    steps:
      # ... continue with the deployment steps (Download artifact, Deploy to Azure WebApp, Import API into Azure API Management, Logout)
